name: Nexial Automation tests running on Container with Volumes

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
      path: $GITHUB_WORKSPACE  # Use $GITHUB_WORKSPACE directly
      fetch-depth: 0  # Optional, fetch all history if needed

    - name: Build the Docker image
      run: |
        docker build -t nexial .

    - name: Run nexial scripts
      run: |
       docker run -v "$(pwd)/output:/home/projects/tests/output" --name nex nexial

    - name: Get results of Nexial
      if: ${{ ! cancelled() }}
      run: |
              ls -lrta
              cd output
              cd "$(ls -d */ | head -n 1)"

              cat ./execution-detail.json
              failCount=$(jq -r '.failCount' execution-detail.json)
              echo "failCount is $failCount."

              if [ "$failCount" -gt 0 ]; then
                echo "Automation tests failed."
                exit 1
              else
                echo "Automation tests passed."
              fi
    # Grant write permissions to runner user for the parent directory (optional)
    - name: Grant write permissions (optional)
      run: chmod -R u+w /home/runner/work/nexial-docker/nexial-docker/output


    - name: Copy output to workspace (Optional - if not modified Dockerfile)
      run: |
            docker cp nex:/home/projects/tests/output $(pwd)/output

                                           
